
name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x viikko1/NhlStatistics1/gradlew
    - name: Test with Gradle
      run: viikko1/NhlStatistics1/gradlew test
    - name: Code coverage rapost
      run: viikko1/NhlStatistics1/gradlew jacocoTestReport
    - name: Data to codecov
      run: bash <(curl -s https://codecov.io/bash)
